# Generated by Django 5.1.3 on 2025-01-03 09:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_item_slug_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
