# Generated by Django 5.1.3 on 2025-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_description_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempackage',
            old_name='price',
            new_name='bdt_price',
        ),
        migrations.AddField(
            model_name='itempackage',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency_choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
